export const baseline = "d4ca434";

export const slides = [
  {
    chapter: "Why", type: "cover", seconds: 45,
    title: "Agent Airlock",
    subtitle: "Give AI agents room to move, not room to break the rules.",
    hero: "Room to move.\nRules that hold.",
    heroSubtitle: "Agent Airlock checks each mission before takeoff, pauses risky actions for approval,\nand blocks forbidden actions before they reach real systems.",
    coverSteps: ["AGENT PROPOSES", "POLICY DECIDES", "EXECUTE OR STOP"],
    band: "THE PROMPT DESCRIBES THE DESTINATION. AGENT AIRLOCK CLEARS THE SAFE PATH.",
    sources: ["server.mjs:18-84", "runtime/broker.mjs:20-84"],
    notes: `Open with the canonical repository tagline. The project is about preserving useful agent autonomy while moving permission out of mutable instructions and into reviewed controls. The rest of the presentation answers three questions: what problem are we solving, where is enforcement placed, and what does each gate actually do?`,
  },
  {
    chapter: "Why", type: "cards", seconds: 75,
    title: "AI agents have hands now",
    subtitle: "They do not only recommend actions; they can reach systems that matter.",
    cards: [
      { label: "CODE", title: "Change repositories", body: "Edit files, create branches and prepare pull requests.", color: "cyan" },
      { label: "DATA", title: "Move information", body: "Read logs, drafts and enterprise context—then display or publish it.", color: "purple" },
      { label: "SUPPLY CHAIN", title: "Choose dependencies", body: "Modify manifests, restore packages and introduce new risk.", color: "amber" },
      { label: "OPERATIONS", title: "Trigger effects", body: "Push, publish, invoke models and call external tools.", color: "red" },
    ],
    band: "The risk is not that the agent can reason. The risk is that reasoning can become an effect.",
    sources: ["server.mjs:18-84", "tools/publish-draft.mjs:23-35", "tools/review-dependency-change.mjs:44-63"],
    notes: `Frame the problem in operational terms. An agent can now cross the boundary between proposing and doing. That is valuable, but it means a prompt mistake, poisoned context, unsafe dependency or leaked token can reach a real system. Airlock focuses on the transition from intent to effect.`,
  },
  {
    chapter: "Why", type: "table", seconds: 75,
    title: "Instructions shape behavior. They do not create a security boundary.",
    subtitle: "Repository and personal instructions are useful guidance, but the agent still needs a separate permission layer.",
    headers: ["Control", "Good for", "Why it is not enforcement"],
    widths: [2.4, 4.2, 5.53],
    rows: [
      ["Prompt", "Describing the desired outcome", "Untrusted text can request exceptions or conflict with policy"],
      ["Repo instructions", "Coding conventions and workflow", "Owned with the workload and interpreted by the model"],
      ["Personal instructions", "Developer preferences", "Different users can carry different guidance"],
      ["Airlock policy", "Permission for protected effects", "Trusted code evaluates a structured action before execution"],
    ],
    band: "Guidance can influence the proposal. Only the guarded path controls the effect.",
    sources: ["runtime/policies.mjs:53-104", "runtime/broker.mjs:43-74", "policies/default.json:1-42"],
    notes: `This is the core distinction. Prompts and instructions remain important, but they are inputs to reasoning. They should not be the authority that grants permission. Airlock keeps reviewed policy and gate code separate, evaluates a structured action, and lets the broker decide whether trusted executor code starts.`,
  },
  {
    chapter: "Concept", type: "airlock", seconds: 75,
    title: "Put a controlled boundary between intent and effect",
    subtitle: "Let the agent explore inside; guard the operations that leave the chamber.",
    band: "The airlock is a transition point: propose freely, execute only after policy clears the action.",
    sources: ["tools/publish-draft.mjs:23-35", "runtime/broker.mjs:61-74", "server.mjs:18-84"],
    notes: `Use the physical airlock metaphor. Work inside the chamber can stay flexible: analysis, edits, tests and draft creation. A protected operation becomes a structured action at the exit. Policy-bound gates inspect that action, a receipt records the result, and the executor is called only after all required checks allow.`,
  },
  {
    chapter: "Structure", type: "flow", seconds: 100,
    title: "The system is structured around one enforcement owner",
    subtitle: "Each component has one job; only the broker controls execution.",
    steps: [
      { title: "Tool adapter", body: "Validates input and constructs a fixed action.", color: "cyan" },
      { title: "Policy", body: "Binds the action to required gates.", color: "purple" },
      { title: "Gates", body: "Return allow, block, ask-first or error.", color: "amber" },
      { title: "Broker", body: "Combines decisions and records evidence.", color: "red" },
      { title: "Executor", body: "Performs only the approved narrow effect.", color: "green" },
    ],
    band: "The model can request a supported action. It cannot supply or invoke the executor.",
    sources: ["server.mjs:18-84", "runtime/broker.mjs:20-84", "runtime/policies.mjs:53-104"],
    notes: `Walk left to right. MCP exposes guarded tools. Each adapter validates caller input and constructs a fixed action and trusted executor callback. Policy selects gates. Gates are read-only evaluators. The broker owns orchestration, decision precedence, receipts and execution. This keeps enforcement centralized rather than scattered across mutable prompts or tool implementations.`,
  },
  {
    chapter: "Structure", type: "sequence", seconds: 100,
    title: "What happens when an action reaches Airlock",
    subtitle: "The exact bytes that are checked are the bytes the executor receives.",
    band: "Decision receipt first. Executor second. Any non-allow result returns without opening the door.",
    sources: ["runtime/broker.mjs:24-84", "runtime/policies.mjs:44-55", "tests/broker.test.mjs:73-83"],
    notes: `The adapter passes a validated action and trusted callback. The broker freezes the action, evaluates every required gate, and saves the decision. Block, error and ask-first stop before execution. On allow, the executor receives the same frozen snapshot. This closes the common time-of-check/time-of-use gap where one payload is reviewed and another is emitted.`,
  },
  {
    chapter: "Structure", type: "cards", seconds: 70,
    title: "Every gate uses the same decision contract",
    subtitle: "Different risks compose because their outputs are deliberately boring.",
    cards: [
      { label: "FORBIDDEN", title: "BLOCK", body: "Policy rejects the action. Execution never starts.", color: "red" },
      { label: "CHECK FAILED", title: "ERROR", body: "A required control failed. Fail closed before the effect.", color: "purple" },
      { label: "HUMAN NEEDED", title: "ASK-FIRST", body: "Pause for review. Today the prototype stops here.", color: "amber" },
      { label: "ALL CLEAR", title: "ALLOW", body: "Every required gate passed. The broker may execute.", color: "green" },
    ],
    band: "A green result from one gate cannot cancel a red result from another.",
    sources: ["runtime/policies.mjs:17-29", "runtime/policies.mjs:83-104", "runtime/broker.mjs:43-67"],
    notes: `The common result contract makes the gate set extensible. The evaluator applies deterministic precedence: block, error, ask-first, allow. All gates still run, so receipts show the complete check set. Safe findings contain identifiers and locations rather than copied secrets or personal values.`,
  },
  {
    chapter: "Gate 1", type: "gate", seconds: 160,
    title: "Sensitive Information Protection",
    subtitle: "Prevent secrets, tokens, personal data and internal-only content from leaking through drafts, logs or display text.",
    gateLabel: "publish_draft / three policy-bound checks",
    purpose: "Inspect outbound text before any publish effect.",
    checks: "Secrets and contextual tokens → block\nPII patterns → ask-first\nINTERNAL-ONLY label → ask-first",
    result: "Only clean or safely remediated content publishes",
    resultColor: "green", accent: "red",
    command: `npm run demo -- --gate sensitive-information`,
    outcomes: [
      { label: "clean", value: "published", color: "green" },
      { label: "secret", value: "blocked", color: "red" },
      { label: "PII / label", value: "review", color: "amber" },
    ],
    recordingFile: "recordings/sensitive-information.mp4",
    takeaway: "Prompt overrides do not beat the detector; blocked and review-required cases create no publish artifact.",
    cue: "Play or record the sensitive-information script. Show clean, secret, override, PII, label and replacement outcomes without displaying raw fixture content.",
    sources: ["policies/default.json:1-10", "gates/sensitive-information/index.mjs:1-38", "gates/secrets/gitleaks.toml:1-26"],
    notes: `This is the strongest demo because it shows both prevention and safe handling. A clean synthetic fixture publishes locally. Secret and token matches block. PII and INTERNAL-ONLY content request review; because approval redemption is unfinished, they stop. An override instruction remains data and does not change the rule. Remediation returns a separate candidate that must be rescanned through a new action. The gate is bounded pattern detection, not a claim of universal DLP.`,
  },
  {
    chapter: "Gate 2", type: "gate", seconds: 120,
    title: "Dependency Risk",
    subtitle: "Review the proposed package and version before editing a manifest or restoring dependencies.",
    gateLabel: "review_dependency_change",
    purpose: "Move dependency review ahead of the irreversible work.",
    checks: "Package identity and proposed version\nReviewed synthetic blocklist\nAdvisory evidence path when available",
    result: "Blocked proposal → no edit, no restore",
    resultColor: "red", accent: "amber",
    command: `npm run demo -- --gate dependency-risk`,
    outcomes: [
      { label: "package", value: "MSAL", color: "cyan" },
      { label: "version", value: "demo-blocked", color: "amber" },
      { label: "effect", value: "not started", color: "red" },
    ],
    recordingFile: "recordings/dependency-risk.mp4",
    takeaway: "The demo is a deterministic synthetic policy case—not a CVE claim about the sample repository.",
    cue: "Play or record dependency-risk. Show the blocked result and unchanged sample worktree.",
    sources: ["gates/dependency-risk/snapshot.json:1-18", "tools/review-dependency-change.mjs:44-63", "tests/dependency-risk.test.mjs:266-292"],
    notes: `The important pattern is sequencing: review a proposal before modifying the repository. The deterministic demo uses Microsoft.Identity.Client version 4.88.0-airlock-demo and rule AIRLOCK-DEMO-001. The sample does not contain that PackageReference, and this is not a real vulnerability claim. For ordinary versions, the implementation can use current or cached advisory evidence.`,
  },
  {
    chapter: "Gate 3", type: "gate", seconds: 100,
    title: "Model Catalog",
    subtitle: "Constrain model selection by task and data classification before inference is requested.",
    gateLabel: "select_model",
    purpose: "Choose only reviewed model routes for the declared context.",
    checks: "Task type and caller-supplied data class\nDefault, permitted override or blocked entry\nCatalog status and policy",
    result: "Default selects; override pauses; blocked model stops",
    resultColor: "amber", accent: "purple",
    command: `npm run demo -- --gate model-catalog`,
    outcomes: [
      { label: "default", value: "selected", color: "green" },
      { label: "override", value: "review", color: "amber" },
      { label: "public", value: "blocked", color: "red" },
    ],
    recordingFile: "recordings/model-catalog.mp4",
    takeaway: "The prototype records a local selection; it does not switch Copilot’s active model or invoke inference.",
    cue: "Play or record model-catalog. Compare default, override and blocked outcomes.",
    sources: ["gates/model-catalog/catalog.json:1-22", "gates/model-catalog/index.mjs:50-77", "tools/select-model.mjs:20-40"],
    notes: `Model choice can be governed as a structured action. The reviewed default allows, a permitted override asks for approval, and a blocked public entry rejects. The declared data class is caller supplied today, not automatically classified. The executor creates a local selection record only; this demonstrates the decision architecture rather than real model routing.`,
  },
  {
    chapter: "Gate 4", type: "gate", seconds: 90,
    title: "Online-Write Intent",
    subtitle: "Detect explicit requests to push or publish before an online-write tool is selected.",
    gateLabel: "check_intent",
    purpose: "Treat forceful wording as intent—not as authorization.",
    checks: "Supplied prompt text\nReviewed online-write patterns\nLocal-review versus external-write intent",
    result: "“/yolo git push …” is still blocked",
    resultColor: "red", accent: "cyan",
    command: `npm run demo -- --gate intent`,
    outcomes: [
      { label: "local review", value: "cleared", color: "green" },
      { label: "push request", value: "blocked", color: "red" },
      { label: "shell", value: "not executed", color: "amber" },
    ],
    recordingFile: "recordings/intent.mp4",
    takeaway: "This gate checks text routed through Airlock; it is not an operating-system shell sandbox.",
    cue: "Play or record intent. Do not execute the prompt as a native command.",
    sources: ["gates/no-online-writes/rules.json:3-12", "gates/no-online-writes/index.mjs:30-44", "tools/check-intent.mjs:6-33"],
    notes: `The memorable point is that “yolo” cannot grant permission. The technical boundary is equally important: this tool checks supplied text. It does not intercept an unrelated native git process, and regex intent checks are not semantic proof. Host mediation is needed to make the check mandatory before arbitrary online-write tools.`,
  },
  {
    chapter: "Gate 5", type: "gate", seconds: 90,
    title: "Trending Cost",
    subtitle: "Surface local usage trends with policy context before cost becomes invisible.",
    gateLabel: "trending_cost",
    purpose: "Make operational usage visible through the same policy surface.",
    checks: "Local CLI usage-style SQLite data\nMonth-to-date cost and current-day usage\nConfigured advisory threshold",
    result: "Above threshold reports an advisory—not a hard block",
    resultColor: "amber", accent: "green",
    command: `npm run demo -- --gate trending-cost`,
    outcomes: [
      { label: "below", value: "reported", color: "green" },
      { label: "above", value: "advisory", color: "amber" },
      { label: "missing", value: "explicit", color: "purple" },
    ],
    recordingFile: "recordings/trending-cost.mp4",
    takeaway: "Synthetic disposable data only; this is not billing, spend reservation or account-wide enforcement.",
    cue: "Play or record trending-cost. Keep the synthetic-data and advisory labels visible.",
    sources: ["policies/trending-cost.json:1-12", "gates/trending-cost/usage.mjs:110-168", "tests/trending-cost.test.mjs:87-172"],
    notes: `This shows that the same policy architecture can cover operational constraints as well as security. The demo uses synthetic local SQLite data. The checked-in policy is advisory at an $800 month-to-date threshold. Above threshold reports context but still completes; atomic reservation and enforced pre-spend blocking are not implemented.`,
  },
  {
    chapter: "Evidence", type: "table", seconds: 90,
    title: "Every decision leaves evidence",
    subtitle: "Receipts explain what was checked and whether the guarded executor ran.",
    headers: ["Receipt field", "Question answered", "Important limit"],
    rows: [
      ["Policy ID + hash", "Which reviewed policy applied?", "Not whole-plugin integrity"],
      ["Gate checks", "Which controls ran and decided?", "Detection remains bounded"],
      ["Safe findings", "What rule and location matched?", "Raw sensitive value is omitted"],
      ["Execution state", "Did this executor start?", "Does not prove no alternate route existed"],
      ["Artifact / error", "What happened after allow?", "External effects may require stronger attestation"],
    ],
    band: "Evidence is part of the control path, not an after-the-fact log message.",
    cue: "Open one allowed and one blocked result.json plus their receipts from the latest scripted run.",
    sources: ["runtime/broker.mjs:37-84", "runtime/policies.mjs:73-77", "tests/publish-draft.test.mjs:26-52"],
    notes: `Receipts distinguish a decision from a status string. They capture policy identity, check results, safe findings, action fingerprint and execution state. Blocked actions show not-started and no business artifact. Allowed actions show the local artifact. Receipts are local evidence in this prototype, not signed compliance attestations.`,
  },
  {
    chapter: "Extensibility", type: "source", seconds: 80,
    title: "Adding a gate is intentionally small",
    subtitle: "New checks plug into a stable result contract without owning the side effect.",
    codeLabel: "Gate shape / safe result",
    code: `{
  id: "reviewed-check",
  failureReason: "check-failed",
  async evaluate(action) {
    return {
      decision: "allow",
      reason: "safe-reason-code",
      findings: []
    };
  }
}`,
    points: [
      { title: "Read-only evaluator", body: "The gate inspects the action; it never performs the protected operation.", color: "cyan" },
      { title: "Explicit composition", body: "Register trusted code, bind it in policy and test all decision paths.", color: "green" },
    ],
    band: "The extension point is the gate. The enforcement owner remains the broker.",
    sources: ["gates/index.mjs:1-16", "runtime/policies.mjs:17-29", "runtime/policies.mjs:58-75", "policies/default.json:1-10"],
    notes: `For engineers, this is the maintainability story. A gate should be a focused, read-only evaluator returning a strict safe result. Registration and policy binding are explicit. Tests should cover allow, block, ask-first, error and composition. The gate never invokes the executor, preserving one orchestration owner and avoiding temporal coupling.`,
  },
  {
    chapter: "Boundary", type: "boundary", seconds: 90,
    title: "What the prototype enforces—and what it does not yet",
    subtitle: "Airlock controls supported actions routed through Airlock. Alternate permitted routes remain the system-level gap.",
    band: "Another MCP or shell route cannot override an Airlock block; it can bypass Airlock if the host still permits that route.",
    sources: [".mcp.json:1-11", "server.mjs:18-84", "hooks/hooks.json:1-13", "runtime/broker.mjs:67-72"],
    notes: `Be explicit about the boundary. On the Airlock route, the broker owns the executor and a block is final. If the host also exposes another publisher, shell or credential path, that is a separate exit. Mandatory enforcement requires host/runtime mediation or destination controls so protected operations cannot happen outside the broker.`,
  },
  {
    chapter: "Path forward", type: "table", seconds: 90,
    title: "The path from prototype to shared enforcement",
    subtitle: "The next milestone is not more warnings. It is making protected routes unavoidable.",
    headers: ["Priority", "Capability", "Proof"],
    rows: [
      ["1", "Mandatory host or destination mediation", "Alternate-route coverage tests"],
      ["2", "Approval redemption bound to the exact action", "Expiry, replay and mutation rejection"],
      ["3", "Protected policy distribution and integrity", "Missing or invalid controls fail closed"],
      ["4", "Narrow real-world executors", "Destination, credential and retry guarantees"],
      ["5", "Broader gate catalog", "New risks compose without weakening existing checks"],
    ],
    band: "Control the door first. Then add more detectors behind it.",
    sources: ["runtime/broker.mjs:43-84", "policies/default.json:1-42", "server.mjs:18-84", "hooks/hooks.json:1-13"],
    notes: `Sequence the roadmap around enforcement. First ensure protected actions have no alternate route. Then implement exact approval redemption. Protect policy deployment and integrity. Add narrow real executors with clear destination and retry behavior. With that foundation, teams can add gates without creating a collection of optional warnings.`,
  },
  {
    chapter: "Takeaway", type: "closing", seconds: 55,
    title: "What we want the team to remember",
    subtitle: "Autonomy and control are not opposites when permission lives at the action boundary.",
    hero: "Give AI agents room to move,\nnot room to break the rules.",
    body: "The prompt describes the destination.\nAgent Airlock clears the safe path.",
    band: "PROPOSE FREELY. CHECK CONSISTENTLY. EXECUTE DELIBERATELY.",
    sources: ["runtime/policies.mjs:58-104", "runtime/broker.mjs:61-84", "server.mjs:18-84"],
    notes: `Close on the canonical message. Airlock does not try to make prompts perfect. It turns protected effects into structured actions, evaluates reviewed policy, records the decision, and controls whether trusted executor code starts. The prototype proves the pattern on explicit Airlock routes. The team discussion is which exits matter first and what integration makes those exits mandatory.`,
  },
];
